import type { Review } from "./types"

export const FALLBACK: Review[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    rating: 5,
    text: "The physiotherapy team helped me recover from my knee injury faster than I expected. Professional, caring, and knowledgeable staff.",
    date: "2024-01-15",
    avatar: "/diverse-woman-smiling.png",
    location: "Kitchener, ON",
    treatment: "Knee Rehabilitation",
  },
  {
    id: "2",
    name: "Mike Chen",
    rating: 5,
    text: "Excellent sports rehab program. Got me back on the field stronger than before my shoulder injury. Highly recommend!",
    date: "2024-01-10",
    avatar: "/man-athlete.png",
    location: "Waterloo, ON",
    treatment: "Sports Rehabilitation",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    rating: 5,
    text: "Amazing experience with the physiotherapy team. They explained everything clearly and made me feel comfortable throughout my treatment.",
    date: "2024-01-08",
    avatar: "/professional-woman.png",
    location: "Cambridge, ON",
    treatment: "Back Pain Treatment",
  },
  {
    id: "4",
    name: "David Thompson",
    rating: 5,
    text: "The staff is incredibly professional and the facility is top-notch. My chronic pain has significantly improved thanks to their expertise.",
    date: "2024-01-05",
    avatar: "/business-man.png",
    location: "Kitchener, ON",
    treatment: "Chronic Pain Management",
  },
  {
    id: "5",
    name: "Lisa Park",
    rating: 5,
    text: "Outstanding care and attention to detail. The personalized treatment plan made all the difference in my recovery.",
    date: "2024-01-03",
    avatar: "/woman-healthcare.jpg",
    location: "Guelph, ON",
    treatment: "Post-Surgery Rehabilitation",
  },
  {
    id: "6",
    name: "James Wilson",
    rating: 5,
    text: "Great location and convenient hours. The physiotherapists are skilled and genuinely care about your progress.",
    date: "2023-12-28",
    avatar: "/casual-man.png",
    location: "Kitchener, ON",
    treatment: "Neck Pain Treatment",
  },
]
